name: Back-End CI

on:
  push:
    paths:
      - 'Back-End/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'Back-End/**'
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./Back-End

    - name: Lint and Test
      run: |
        npm run lint
        npm test
      working-directory: ./Back-End

    - name: Build Back-End
      run: npm run build
      working-directory: ./Back-End
